language: node_js
deploy:
  provider: npm
  email: sandbox_JSUI@coveo.com
  api_key:
    secure: CsRAOjw3GCfawyyGy1ICScdA6T3N1S8XPCGqzVVM7tGrRPHBQeuAnw872P5Xgafi89JJ527lZXNqqKTfIcM1S4KZj6xLLYS641gMGbzx+SZ+RhSTZm97ECge3LYFyisM+3NIuiCAi9lgTa+JoOtplUVS0pSpqsVppXvPqsFavUVik7gv5THxFpx80iXDcWHufMoynZFodGC921DWKlC4SxQD5rZhG9XoGTYr36Ox0PuUjZRNgxU8gEhdgGLWKIRZrCfzWhtb2SAjvG28AzXT1VLb2BbnYCe44EMLqsOTcfzbFZEPR7gFyjZ8qCbLwUNkTHKtSA7NPfCHBl/bmFaBGjTNAzqv5Ne7jEXpB3olmz06q58QXybk1IYewuikKM/wbHUo8KIMv2Hf7VJP3RO8o1GvOPEm/Caif6LTVgQ7E+T7247Sr42EhjmLOFnngKS1UOqHppzuhzRkKkCu9rIT1T83QzD0eWL5lD3+dfLvAB/AGHdxb+m+1it/IUrTSKj+9cM78C/Sj1Ed0TYyDTYC6VgCGNnPMqPfBIpP8r4+SYlkjbcPX8DgygzTd9eDMI0RBXE2IbSBrWQEoQqFBt8tDQdLu51JjYdororVG2Y1SgL5mcK+w8WOHCPJFfUlVPIfGERcvo/J/y8c79GtdmlNVFUz+pymseCvJp3xWmF3pas=
  on:
    repo: coveo/generator-coveo
